# template version 2023.3

services:
  build:
    entrypoint:
      - /bin/sh
      - build.sh
    image: python:${IMAGE_TAG}
    platform: ${PLATFORM:-linux/amd64}
    volumes:
      - ./:/workspace
    working_dir: /workspace
